# Generated by Django 5.2 on 2025-04-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'products', 'verbose_name_plural': 'Products'},
        ),
    ]
