# Generated by Django 5.2 on 2025-05-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_products_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='slug',
            new_name='product_slug',
        ),
    ]
